# Generated by Django 6.0.6 on 2026-07-08 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('visitors', '0010_alter_visitor_card_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='visit',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_purpose', models.CharField(max_length=255)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Checked In', 'Checked In'), ('Checked Out', 'Checked Out')], default='Checked In', max_length=20)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.sys_emp_master')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visitors.visitor')),
                ('visitor_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visitors.visitor_card')),
            ],
        ),
    ]
