# Generated by Django 6.0.6 on 2026-06-27 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employee'),
        ('visitors', '0002_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='visit',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('purpose_of_visit', models.CharField(max_length=255)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='visitors.visitor_card')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='employees.employee')),
                ('vistor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='visitors.visitor')),
            ],
        ),
    ]
