# Generated by Django 6.0.6 on 2026-06-29 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_employee_cnic'),
        ('visitors', '0008_visitor_card_is_available_and_more'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='purpose_of_visit',
            new_name='visit_purpose',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='card_id',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='vistor_id',
        ),
        migrations.AddField(
            model_name='visit',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee'),
        ),
        migrations.AddField(
            model_name='visit',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visitors.visitor'),
        ),
        migrations.AddField(
            model_name='visit',
            name='visitor_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visitors.visitor_card'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('Checked In', 'Checked In'), ('Checked Out', 'Checked Out')], default='Checked In', max_length=20),
        ),
    ]
