# Generated by Django 6.0.6 on 2026-07-17 09:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='is_backlog',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visit',
            name='check_in_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
