# Generated by Django 6.0.6 on 2026-07-17 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_visit_is_backlog_alter_visit_check_in_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'permissions': [('can_view_backlogs', 'Can view backlogs')]},
        ),
    ]
