# Generated by Django 6.0.6 on 2026-06-27 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_email', models.EmailField(max_length=254, unique=True)),
                ('employee_phone', models.CharField(max_length=11)),
                ('employee_cnic', models.CharField(max_length=20, unique=True)),
                ('employee_designation', models.CharField(max_length=100)),
                ('employee_created_at', models.DateTimeField(auto_now_add=True)),
                ('employee_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.department')),
            ],
        ),
    ]
