# Generated by Django 6.0.6 on 2026-06-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_cnic',
        ),
    ]
