# Generated by Django 6.0.6 on 2026-06-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('company_domain', models.CharField(blank=True, max_length=150, null=True)),
                ('primary_color', models.CharField(default='#cb0c9f', max_length=20)),
                ('secondary_color', models.CharField(default='#8392ab', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
