# Generated by Django 6.0.6 on 2026-06-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='logo_color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
    ]
