# Generated by Django 6.0.6 on 2026-06-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0002_systemsettings_logo_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='logo',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='company_name_short',
            field=models.CharField(default='HNL', max_length=10),
        ),
    ]
