# Generated by Django 6.0.6 on 2026-06-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0003_remove_systemsettings_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='company_name_short',
        ),
    ]
