# Generated by Django 6.0.6 on 2026-06-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0004_remove_systemsettings_company_name_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='company_name_short',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
