# Generated by Django 6.0.6 on 2026-07-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0005_systemsettings_company_name_short'),
    ]

    operations = [
        migrations.CreateModel(
            name='system_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(upload_to='company/')),
                ('password_algorithm', models.CharField(default='PBKDF2', max_length=50)),
                ('session_timeout', models.IntegerField(default=30)),
                ('password_expiry_days', models.IntegerField(default=90)),
                ('password_min_length', models.IntegerField(default=8)),
            ],
        ),
    ]
