# Generated by Django 6.0.6 on 2026-07-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0006_system_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='system_settings',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='password_algorithm',
            field=models.CharField(default='PBKDF2', max_length=50),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='password_expiry_days',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='password_min_length',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='session_timeout',
            field=models.IntegerField(default=30),
        ),
    ]
