# Generated by Django 6.0.6 on 2026-07-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0007_delete_system_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='ms_client_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MS Client ID'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ms_client_secret',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='MS Client Secret'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ms_redirect_uri',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MS Redirect URI'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ms_tenant_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MS Tenant ID'),
        ),
    ]
