# Generated by Django 6.0.6 on 2026-07-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserManagementPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_users', 'Can view users'), ('add_users', 'Can add users'), ('change_users', 'Can change users'), ('delete_users', 'Can delete users')],
                'managed': False,
            },
        ),
    ]
