# Generated by Django 6.0.6 on 2026-07-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_reports', 'Can view reports'), ('download_reports', 'Can download reports')],
                'managed': False,
            },
        ),
    ]
