# Generated by Django 6.0.6 on 2026-07-08 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sys_bra_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bra_code', models.CharField(max_length=10, unique=True)),
                ('bra_desc', models.CharField(max_length=150)),
                ('bra_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='sys_cmp_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cmp_code', models.CharField(max_length=10, unique=True)),
                ('cmp_desc', models.CharField(max_length=150)),
                ('cmp_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='sys_div_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('div_code', models.CharField(max_length=10, unique=True)),
                ('div_desc', models.CharField(max_length=150)),
                ('div_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='sys_pur_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pur_id', models.CharField(max_length=10, unique=True)),
                ('pur_purpose', models.CharField(max_length=100)),
                ('pur_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='sys_dep_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dep_code', models.CharField(max_length=10, unique=True)),
                ('dep_desc', models.CharField(max_length=150)),
                ('dep_active', models.BooleanField(default=True)),
                ('dep_div_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.sys_div_master')),
            ],
        ),
        migrations.CreateModel(
            name='sys_emp_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_pno', models.CharField(max_length=50, unique=True)),
                ('emp_name', models.CharField(max_length=150)),
                ('emp_designation', models.CharField(max_length=150)),
                ('emp_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emp_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('emp_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('emp_pbx', models.CharField(blank=True, max_length=20, null=True)),
                ('emp_active', models.BooleanField(default=True)),
                ('emp_bra_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.sys_bra_master')),
                ('emp_cmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.sys_cmp_master')),
                ('emp_dep_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.sys_dep_master')),
            ],
        ),
        migrations.CreateModel(
            name='sys_usr_system',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usr_pno', models.CharField(max_length=50, unique=True)),
                ('usr_name', models.CharField(max_length=150)),
                ('usr_designation', models.CharField(max_length=150)),
                ('usr_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('usr_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('usr_email', models.EmailField(max_length=254, unique=True)),
                ('usr_auth', models.CharField(blank=True, max_length=50, null=True)),
                ('usr_loginID', models.CharField(max_length=100, unique=True)),
                ('usr_password', models.CharField(blank=True, max_length=255, null=True)),
                ('usr_access_group', models.CharField(max_length=100)),
                ('usr_bra_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.sys_bra_master')),
                ('usr_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.sys_cmp_master')),
                ('usr_dep_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.sys_dep_master')),
            ],
        ),
    ]
