# Generated by Django 6.0.6 on 2026-07-10 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sys_usr_system',
            name='usr_bra_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.sys_bra_master'),
        ),
        migrations.AlterField(
            model_name='sys_usr_system',
            name='usr_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.sys_cmp_master'),
        ),
        migrations.AlterField(
            model_name='sys_usr_system',
            name='usr_dep_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.sys_dep_master'),
        ),
    ]
