# Generated by Django 6.0.6 on 2026-07-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_alter_sys_usr_system_usr_bra_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sys_usr_system',
            name='usr_is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sys_usr_system',
            name='usr_is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sys_usr_system',
            name='usr_is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
