# Generated by Django 6.0.6 on 2026-06-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visitor_card',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_color', models.CharField(max_length=50, unique=True)),
                ('card_access_level', models.CharField(max_length=100)),
            ],
        ),
    ]
