# Generated by Django 6.0.6 on 2026-07-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visitor',
            fields=[
                ('visitor_id', models.AutoField(primary_key=True, serialize=False)),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_email', models.EmailField(max_length=254, unique=True)),
                ('visitor_phone', models.CharField(max_length=15)),
                ('visitor_address', models.CharField(blank=True, max_length=255, null=True)),
                ('visitor_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='visitor_card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CRD_No', models.CharField(max_length=50, unique=True)),
                ('CRD_Desc', models.CharField(max_length=150)),
                ('CRD_Active', models.BooleanField(default=True)),
            ],
        ),
    ]
