# Generated by Django 6.0.6 on 2026-07-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='visitor_email',
        ),
        migrations.AddField(
            model_name='visitor',
            name='visitor_cnic',
            field=models.CharField(default=' ', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_address',
            field=models.CharField(max_length=255),
        ),
    ]
