# Generated by Django 6.0.6 on 2026-06-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitor',
            fields=[
                ('visitor_id', models.AutoField(primary_key=True, serialize=False)),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_email', models.EmailField(max_length=254, unique=True)),
                ('visitor_phone', models.CharField(max_length=15)),
                ('visitor_cnic', models.CharField(max_length=20, unique=True)),
                ('visitor_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
