# Generated by Django 6.0.6 on 2026-06-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='visitor_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
