# Generated by Django 6.0.6 on 2026-07-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_remove_visitor_visitor_email_visitor_visitor_cnic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visitor_cnic',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
