# Generated by Django 6.0.6 on 2026-06-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_visitor_visitor_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='visitor_cnic',
        ),
    ]
