# Generated by Django 6.0.6 on 2026-07-24 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_company_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='company_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visitors.company_type'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visitor_company',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
