# Generated by Django 6.0.6 on 2026-06-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_remove_visitor_visitor_cnic'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor_card',
            name='card_number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
