# Generated by Django 6.0.6 on 2026-06-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_visitor_card_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor_card',
            name='card_color',
            field=models.CharField(max_length=50),
        ),
    ]
