# Generated by Django 6.0.6 on 2026-06-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0006_alter_visitor_card_card_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor_card',
            name='card_number',
            field=models.CharField(default=0, max_length=5, unique=True),
        ),
    ]
