# Generated by Django 6.0.6 on 2026-06-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0007_alter_visitor_card_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor_card',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='visitor_card',
            name='card_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
