# Generated by Django 6.0.6 on 2026-06-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0008_visitor_card_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor_card',
            name='card_number',
            field=models.CharField(max_length=20),
        ),
    ]
