# Generated by Django 6.0.6 on 2026-06-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0009_alter_visitor_card_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor_card',
            name='card_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
